# Use container-based infrastructure
sudo: false

language: node_js

node_js:
  - 'stable'

cache:
  directories:
    # Cache local bower cache files for faster install
    - $HOME/.cache/bower

before_deploy:
  - npm run build

deploy:
  provider: script
  script:
    - 'echo "TODO: deploy the app. Directory listing:" && ls -R dist'
  skip_cleanup: true
  on:
    branch: master
